### ISSUE TITLE
Install results in MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by PBXForums** [william89731/node-red-contrib-ssh-v3#1]
After installing, either through command line or gui the above is shown in the pallete.

**Comment by frg11h14** [comment]
same for me, even after node red upgrade:

  Stop Node-RED                       ✔
  Remove old version of Node-RED      ✔
  Node option not specified           :   --node14, --node16, or --node18
  Leave existing Node.js              :   v17.5.0   Npm 8.4.1
  Clean npm cache                     -
  Install Node-RED core               ✔   3.0.1
  Move global nodes to local          -
  Leave existing nodes                -
  Install extra Pi nodes              -
  Add shortcut commands               ✔
  Update systemd script               ✔

**Comment by vdwpsmt** [comment]
Same here, in node-red logs I get a warning when starting this package about a missing module: 

> Error: Cannot find module 'async-mutex'
