### ISSUE TITLE
Node-red crashes trying to remove this node

### ISSUE THREAD

**Issue by juggledad** [william89731/node-red-contrib-ssh-v3#10]
14 Sep 05:34:21 - [info] Starting modified flows
14 Sep 05:34:21 - [red] Uncaught Exception:
14 Sep 05:34:21 - [error] TypeError: Cannot read properties of undefined (reading 'update')
    at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:377:31)
paul@PaulsM1 ~ %

**Comment by william89731** [comment]
in nodeRed dir, rename folder ```node_modules``` and ```package-lock.json```. in ```package.json```, leave ```node-red-contrib-ssh-v3```.  
launch 
```bash 
npm i
