### ISSUE TITLE
async-mutex missing?

### ISSUE THREAD

**Issue by waldbaer** [william89731/node-red-contrib-ssh-v3#11]
Hi @william89731 ,

on a fresh Node-RED 3.1.0 installation I get the following warning when installing ssh-v3 during startup:

```
Welcome to Node-RED
===================

16 Oct 18:38:44 - [info] Node-RED version: v3.1.0
16 Oct 18:38:44 - [info] Node.js  version: v20.8.0
16 Oct 18:38:44 - [info] Linux 6.5.7-arch1-1 x64 LE
16 Oct 18:38:46 - [info] Loading palette nodes
16 Oct 18:38:48 - [info] Dashboard version 3.6.0 started at /ui
16 Oct 18:38:49 - [warn] ------------------------------------------------------
16 Oct 18:38:49 - [warn] [node-red-contrib-ssh-v3/ssh-v3] Error: Cannot find module 'async-mutex'
Require stack:
- /home/x/.node-red/node_modules/node-red-contrib-ssh-v3/ssh.js

```

With manual installation of async-mutex I can at least start Node-RED:
```
npm install async-mutex
```

But I guess there is some dependency missing!?

Thanks

**Comment by william89731** [comment]
> Hi @william89731 ,
> 
> on a fresh Node-RED 3.1.0 installation I get the following warning when installing ssh-v3 during startup:
> 
> ```
> Welcome to Node-RED
> ===================
> 
> 16 Oct 18:38:44 - [info] Node-RED version: v3.1.0
> 16 Oct 18:38:44 - [info] Node.js  version: v20.8.0
> 16 Oct 18:38:44 - [info] Linux 6.5.7-arch1-1 x64 LE
> 16 Oct 18:38:46 - [info] Loading palette nodes
> 16 Oct 18:38:48 - [info] Dashboard version 3.6.0 started at /ui
> 16 Oct 18:38:49 - [warn] ------------------------------------------------------
> 16 Oct 18:38:49 - [warn] [node-red-contrib-ssh-v3/ssh-v3] Error: Cannot find module 'async-mutex'
> Require stack:
> - /home/x/.node-red/node_modules/node-red-contrib-ssh-v3/ssh.js
> ```
> 
> With manual installation of async-mutex I can at least start Node-RED:
> 
> ```
> npm install async-mutex
> ```
> 
> But I guess there is some dependency missing!?
> 
> Thanks

to solved, follow #6
