### ISSUE TITLE
Stops flows after installation

### ISSUE THREAD

**Issue by novski** [william89731/node-red-contrib-ssh-v3#14]
![Bildschirmfoto 2024-01-02 um 14 32 09](https://github.com/william89731/node-red-contrib-ssh-v3/assets/6088056/1e59b7f8-ee62-4e90-bcae-a00e2f0f1344)

**Comment by kafelnikovs** [comment]
same problem here....
when i try to uninstall it just can't 
any solution @william89731 ?

**Comment by oxivanisher** [comment]
Can confirm. This node is currently broken (at least with Node-RED v3.1.5).

**Comment by oxivanisher** [comment]
I just tested this with the current 4.0.2 node red and the problems still exists. I "solved" it for me by using the "exec" node and calling ssh myself.

I am using this to trigger WOL in another network (WOL packages are not routable). For this, I configured SSH on the WOL host like this:

In USERs `.ssh/authorized_keys`:
```plaintext
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="/usr/bin/wakeonlan $SSH_ORIGINAL_COMMAND" ssh-ed25519 AAAAC3NzaMSSUPERSECURESSHKEYlkajsldijalskdjfglaisjdlay another_user@nodered_host
```
This will allow this SSH key to only run the `/usr/bin/wakeonlan` command with the $SSH_ORIGINAL_COMMAND command sent as option.

Then the exec node I set:
Command: `ssh -v USER@the_wol_host.example.com -i /home/another_user/.ssh/id_ed25519_nodered`
Append: `☑️ msg.payload`

Now i only need to send a MAC address to this exec node and it will ssh to the target host and call it. Maybe this helps somebody get SSH from nodered to work.

**Comment by novski** [comment]
And how it does! Thx!

**Comment by fc-projects** [comment]
Hi guys,

I had the same problem. This is due to async-mutex dependency added in the code but not documented in the package.
While waiting for a fix you can install it manually by going to your "~.nodered/node-modules" folder and run "npm install aync-mutex". Then restart nodered service or reboot your system.

**Comment by william89731** [comment]
bump to 2.0.5
