### ISSUE TITLE
reconnect feature

### ISSUE THREAD

**Issue by platinum55** [william89731/node-red-contrib-ssh-v3#17]
Hello,

when node-red starts and the ssh server is not (yet) available, it seems there are no reconnect tries. Could you possibly implement a reconnect feature? Maybe also with a configurable reconnect timer :-)

**Comment by william89731** [comment]
use inject node for reconnect after restart nodered

![image](https://github.com/user-attachments/assets/c4112d11-87f9-46e7-be17-f77b5abdc91d)

**Comment by platinum55** [comment]
yes, right - thanks!
