### ISSUE TITLE
Enhancement - implementing input from msg (nodered) 

### ISSUE THREAD

**Issue by danielelopez1** [william89731/node-red-contrib-ssh-v3#3]
Hello williamstyle,
about your node node-red-contrib-ssh-v3 on nodered, is working fine, but can you please implement "external" input from msg?
for example another node send msg.ssh.hostname for hostname, msg.ssh.username for username and msg.ssh.sshkey for ssh. 
It would be nice cause it will allow some scripting whith this node. 
thank you

**Comment by william89731** [comment]
hy daniele,
I plan to add new features in the future

**Comment by marvagabi** [comment]
Was this ever implemented? This is breaking my heart testing as I can't pass in the host for a dynamic configuration I'm trying to do.
