### ISSUE TITLE
Can't unninstall

### ISSUE THREAD

**Issue by Curros** [william89731/node-red-contrib-ssh-v3#4]
After stopped, rebooted, restart, etc. I can't uninstall this node.

![image](https://user-images.githubusercontent.com/600906/194936652-f04de3ba-87e1-4688-bfca-2a65fc811a9a.png)

And after clicking remove...
![image](https://user-images.githubusercontent.com/600906/194936703-0b007c6a-dd23-475f-9928-47ed7ba1906c.png)

Event log...
![image](https://user-images.githubusercontent.com/600906/194936832-18c322b1-8a4c-44c5-9b1e-ee5ef77b2366.png)

PD: I can successfully uninstall other nodes.

**Comment by william89731** [comment]
in nodered dir, "npm uninstall node-red-contrib-ssh-v3"
