### ISSUE TITLE
Details in ssh-conf vanish

### ISSUE THREAD

**Issue by hrafnkel** [william89731/node-red-contrib-ssh-v3#6]
I add all the fields into ssh-conf and the deloy only to see the popup with the message; "Flows stopped due to missing node types: ssh-conf and ssh-v3". When I go into the conf all of the fields which I completed are empty again.

I've had a good try, several hours, but I give up now. I'm sorry to say I didn't find the readme to be helpful.

Host: Raspberry Pi 3+
O/S: Raspbian 5.15.84-v7+ #1613
NPM: 9.3.1
NodeJS: 18.14.0

**Comment by frabnet** [comment]
Same thing happening on my OrangePi Zero.

Linux orangepizero 5.15.74-sunxi #22.08.6 SMP Tue Oct 18 07:00:33 UTC 2022 armv7l GNU/Linux
npm version 6.14.17
nodered 3.0.2

During node install some errors displays:
```
2023-05-17T09:02:10.670Z [err] In file included from ../src/binding.cc:1:
2023-05-17T09:02:10.670Z [err] /home/frab/.cache/node-gyp/14.21.0/include/node/node.h:793:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
2023-05-17T09:02:10.670Z [err]   793 |       (node::addon_register_func) (regfunc),                          \
2023-05-17T09:02:10.670Z [err]       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-05-17T09:02:10.670Z [err] /home/frab/.cache/node-gyp/14.21.0/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
2023-05-17T09:02:10.670Z [err]   827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
2023-05-17T09:02:10.670Z [err]       |   ^~~~~~~~~~~~~
2023-05-17T09:02:10.670Z [err] ../src/binding.cc:152:1: note: in expansion of macro ‘NODE_MODULE’
2023-05-17T09:02:10.670Z [err]   152 | NODE_MODULE(cpufeatures, init)
2023-05-17T09:02:10.670Z [err]       | ^~~~~~~~~~~

```

**Comment by william89731** [comment]
you solved?

**Comment by frabnet** [comment]
Not solved, the same error keeps showing:

![immagine](https://github.com/william89731/node-red-contrib-ssh-v3/assets/26867706/67256d7a-8354-4de9-b8fe-c0862c0a734d)

But something changed: when configuring node, settings are kept, fields does not get empty.
Also logs changed a bit. During node install via Nodered:

```
1 Sep 22:31:00 - [info] Installing module: node-red-contrib-ssh-v3, version: 2.0.3
1 Sep 22:31:45 - [info] Installed module: node-red-contrib-ssh-v3
1 Sep 22:31:45 - [info] Added node types:
1 Sep 22:31:45 - [info]  - node-red-contrib-ssh-v3:ssh-conf : Error: Cannot find module 'async-mutex'
Require stack:
- /home/frab/.node-red/node_modules/node-red-contrib-ssh-v3/ssh.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

```

Same error also while starting Node-RED:

```
Welcome to Node-RED
===================

1 Sep 22:23:17 - [info] Node-RED version: v3.0.2
1 Sep 22:23:17 - [info] Node.js  version: v14.21.0
1 Sep 22:23:17 - [info] Linux 5.15.74-sunxi arm LE
1 Sep 22:23:21 - [info] Loading palette nodes
1 Sep 22:23:28 - [warn] ------------------------------------------------------
1 Sep 22:23:28 - [warn] [node-red-contrib-ssh-v3/ssh-v3] Error: Cannot find module 'async-mutex'
Require stack:
- /home/frab/.node-red/node_modules/node-red-contrib-ssh-v3/ssh.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
1 Sep 22:23:28 - [warn] ------------------------------------------------------
```

**Comment by william89731** [comment]
in nodeRed dir, rename folder ```node_modules``` and ```package-lock.json```. 
launch 
```bash 
npm i

**Comment by hazymat** [comment]
> in nodeRed dir, rename folder `node_modules` and `package-lock.json`. launch
> 
> ```shell
> npm i
> ```

No - that doesn't fix it. I'm afraid as soon as I fill in the configuration node and deploy, I get:

```
Flows stopped due to missing node types.
ssh-conf
ssh-v3
```
And the credentials and server IP disappear from the configuration node.

Just doesn't work.

**Comment by william89731** [comment]
> > in nodeRed dir, rename folder `node_modules` and `package-lock.json`. launch
> > ```shell
> > npm i
> > ```
> 
> No - that doesn't fix it. I'm afraid as soon as I fill in the configuration node and deploy, I get:
> 
> ```
> Flows stopped due to missing node types.
> ssh-conf
> ssh-v3
> ```
> 
> And the credentials and server IP disappear from the configuration node.

paste any info to reproduce this issue (nodeRed environment...)
