### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by averlon** [william89731/node-red-contrib-ssh-v3#8]
On a CCU3 in the Palette-view I get the message "module not found".
When deploying, I get the message "flows stopped as nodes not found" (similar, but not exactly).

How can I find out what is missing and solve the issue?

**Comment by averlon** [comment]
anyone hat home?

**Comment by william89731** [comment]
are you paying me for my work and for it to solve your problems? obviously not...
you join by my telegram group asking for help and I replied. you left without leaving feedback, so I'm closing the issue here

**Comment by averlon** [comment]
I didn't want to hijack the telegram group. Therefore I only used it to get in touch with you.
If I remeber correct, you told you will answer on github. By this I assumed a) the reply you gave on TELEGRAM would be repeated on this github issue and b) any further discussion would take place here!

So, from my point of view, no reason to get angry!

**Comment by carlo-de-bernardo** [comment]
Hi William,
I don't know if it is okay to comment here or open a new issue for the same problem. 
I have the same problem on two different machines (ubuntu and raspberry) both running Node-RED 3.0.2.
I am available for any testing you deem appropriate. 
Thanks in advance
Carlo

**Comment by carlo-de-bernardo** [comment]
I've altro tried to upgrade to Node-RED 3.1.0 with non success.
