### ISSUE TITLE
'Help' in dashboard shows two nodes and neither has any information

### ISSUE THREAD

**Issue by juggledad** [william89731/node-red-contrib-ssh-v3#9]
1) Why are both **ssh-conf** and **ssh-v3** showing in the Help tab?
![Screenshot 2023-09-14 at 5 25 15 AM](https://github.com/william89731/node-red-contrib-ssh-v3/assets/11473405/25851dd7-46fd-4fb7-8496-463ad815a060)

2) You need to provide documentation in the Help section of the dashboard to explain what each of the options are. How is anyone suppose to know what each option needs to be and what it refers to. For example, do you need to fill in the **Ssh** option if you have filled in the **Username** and **Password** options?

**Comment by william89731** [comment]
Is it necessary to open two issues at the same time for different issues? 
the information regarding the node can be found in the readme. 
soon they will also be added in the "help" section of nodeRed
